image:
  file: .gitpod.dockerfile  # Opcional, solo si necesitas un Dockerfile personalizado

tasks:
  - init: ./gradlew build   # Comando que se ejecutará al iniciar el entorno
  - command: ./gradlew run   # Comando que se ejecutará para iniciar la aplicación

ports:
  - port: 8080               # Asegúrate de que este sea el puerto que tu aplicación usa
    onOpen: open-preview      # Esto abrirá el puerto automáticamente en una nueva pestaña