ktor:
    deployment:
        port: 8080
        host: "192.168.100.53"
    application:
        modules:
            - com.example.ApplicationKt.module
    mongo:
        uri: "mongodb://localhost:27017" # O el valor que quieras
        database: "encontros" # O el valor que quieras
